spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:1111}

spring.jpa.hibernate.ddl-auto=${SPRING_DDL_AUTO:create}

spring.jpa.show-sql=${SPRING_SHOW_SQL:true}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL:DEBUG}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOGGING_DESCRIPTOR:TRACE}



